export enum STORAGE_KEY {
  C2D_INTERVAL = "C2D_INTERVAL",
  C2D_TAB = "C2D_TAB",
  C2D_AUTO_START = "C2D_AUTO_START",
  C2D_START_STOP = "C2D_START_STOP",
  C2D_IMMEDIATE_START = "C2D_IMMEDIATE_START",
}
